### ISSUE TITLE
Bug #3: Adding Task in Todo Page Retains Information

### ISSUE THREAD

**Issue by pnshinde** [Plantain497/frontend#51]
A user found that adding a second task retains the first added task’s information in the task entry fields. This is located on the Todo page, and all fields are retained from the previously added task (title, date, description). After hearing about the issue, we investigated this and found that it persists in both web and mobile views.

Roadmap to Fix:
- [ ] Investigate text entry form component
- [ ] Fix in web view
- [ ] Fix in mobile view
